# Generated by Django 6.0.3 on 2026-03-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
