# Generated by Django 6.0.3 on 2026-03-26 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champs', '0002_champion_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='riot_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='ChampionBuildInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_region', models.CharField(blank=True, max_length=20)),
                ('sample_size', models.IntegerField(default=0)),
                ('win_rate', models.FloatField(default=0.0)),
                ('recommended_items', models.JSONField(blank=True, default=list)),
                ('recommended_runes', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('champion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='build_insight', to='champs.champion')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
