# Generated by Django 6.0.3 on 2026-03-28 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('champs', '0003_champion_riot_id_championbuildinsight'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
