# Generated by Django 6.0.3 on 2026-03-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champs', '0004_alter_review_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='abilities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='champion',
            name='passive_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='champion',
            name='passive_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='champion',
            name='passive_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
